version: "3.7"
services:
  una-health-app-db:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=una_health_app
    ports:
      - 5432:5432
    volumes:
      - una_health_app_db_data:/var/lib/postgresql/data/


  una-health-app-test-db:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - 5433:5432
    volumes:
      - una_health_app_test_db_data:/var/lib/postgresql/data/


volumes:
  una_health_app_db_data:
    driver: "local"
    name: "una_health_app_db_data"

  una_health_app_test_db_data:
    driver: "local"
    name: "una_health_app_test_db_data"
  