# Generated by Django 5.0.4 on 2024-07-24 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Gerät', models.CharField(max_length=50)),
                ('Seriennummer', models.UUIDField()),
                ('Aufzeichnungstyp', models.IntegerField()),
                ('Gerätezeitstempel', models.DateTimeField()),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Glukosewert_Verlauf', models.IntegerField()),
            ],
        ),
    ]
