# Generated by Django 5.0.4 on 2024-07-24 19:42

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glucoselevel',
            old_name='glucose_value',
            new_name='Aufzeichnungstyp',
        ),
        migrations.RenameField(
            model_name='glucoselevel',
            old_name='timestamp',
            new_name='Gerätezeitstempel',
        ),
        migrations.RemoveField(
            model_name='glucoselevel',
            name='user',
        ),
        migrations.AddField(
            model_name='glucoselevel',
            name='Gerät',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glucoselevel',
            name='Glukosewert_Verlauf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glucoselevel',
            name='Seriennummer',
            field=models.UUIDField(default=uuid.uuid4()),
           
        ),
        migrations.AddField(
            model_name='glucoselevel',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4(), editable=False),
        ),
        migrations.AlterField(
            model_name='glucoselevel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4(), editable=False, primary_key=True, serialize=False),
        ),
    ]
